version: '3'

services:
    php:
        container_name: $COMPOSE_PROJECT_NAME-php
        build:
            context: ./.docker/php
        env_file:
            -   .env.local
        volumes:
            - .:/app
        working_dir: /app
        environment:
            - PHP_IDE_CONFIG=serverName=${REQUEST_HOST:-localhost}
        depends_on:
            - database
        networks:
            - network
        extra_hosts:
            - "host.docker.internal:host-gateway"

    database:
        container_name: $COMPOSE_PROJECT_NAME-mysql
        env_file:
            - .env.local
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/db/data:/var/lib/mysql:rw
        networks:
            - network

    nginx:
        container_name: $COMPOSE_PROJECT_NAME-nginx
        image: nginx
        env_file:
            - .env.local
        volumes:
            - .:/app
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.docker/nginx/templates:/etc/nginx/templates:ro
        ports:
            - "80:80"
        environment:
            - NGINX_SERVER_NAME=${REQUEST_HOST:-localhost}
            - NGINX_PORT=80
        networks:
            - network
        depends_on:
            - php

volumes:
    db-data:

networks:
    network:
